package com.jessematty.black.tower.Components.Base;

import com.badlogic.ashley.core.Component;

import java.util.UUID;

/**
 * component for  an entities unique   id. The is by default  generated by a java  UUID  all  entities are referenced by this in the world;
 * once created  and ID CANNOT be changed
 */
public class EntityId implements Component {
    /**
     *  the entities id;
     */
    private  final  String id;

    public String getId() {
        return id;
    }

    public EntityId() {
        id= UUID.randomUUID().toString();;
    }

    public EntityId(String id) {
        this.id = id;
    }
}
