package com.jessematty.black.tower.Editor.OldClasses;

public enum GameThingTypes {
    PLANT, PROCEDURAL_TREE, BITMASKED_PLANT,  ITEM, SOLIDER, NPC, ENEMY, MAMMAL, REPTILE, BIRD,  FISH,  RING, BOWED_WEAPON, MEELE_WEAPON, POTION, ARMOR, WAND, FOOD, LIQUID, GAS, RIVER,  SIGN, TOMBSTONE, STATUE,  BIT_MASKED_THING,
    ANIMATED_THING, PROJECTILE, ITEM_ACTION, LAMP,  MATERIAL, ANIMATED_ITEM, FIGHTER_EQUIPED_ANIMATED_ITEM,  PROBLEM, ABILITY, CRAFT, ITEM_CONTIANER, FACTORY, TILE,
}
