package com.jessematty.black.tower.Editor.EditMode.Windows.OptionPaneWindows;

public enum StatKinds {
    NUMERIC_STAT, STRING_STAT, BOOLEAN_STAT , NUMERIC_STAT_CHANGEABLE, STRING_STAT_CHANGEABLE,
    BOOLEAN_STAT_CHANGEABLE, NUMERIC_STAT_COLOR_CHANGEABLE , NUMERIC_STAT_TILE_CHANGEABLE
}
